//查询告警列表
export const AlarmGetTypes = {
    REQUESTING: `REQUEST_GET_ALARM`,
    REQUEST_SUCCESS: `GET_ALARM_SUCCESS`,
    REQUEST_ERROR: `GET_ALARM_ERROR`,
}
//告警统计
export const AlarmCountGetTypes = {
    REQUESTING: `REQUEST_GET_ALARM_COUNT`,
    REQUEST_SUCCESS: `GET_ALARM_COUNT_SUCCESS`,
    REQUEST_ERROR: `GET_ALARM_COUNT_ERROR`,
}
//查询告警详细
export const AlarmDetailGetTypes = {
    REQUESTING: `REQUEST_GET_ALARM_DETAIL`,
    REQUEST_SUCCESS: `GET_ALARM_DETAIL_SUCCESS`,
    REQUEST_ERROR: `GET_ALARM_DETAIL_ERROR`,
}
//确认告警
export const checkAlarmTypes = {
    REQUESTING: `REQUEST_PUT_ALARM_CHECK`,
    REQUEST_SUCCESS: `PUT_ALARM_CHECK_SUCCESS`,
    REQUEST_ERROR: `PUT_ALARM_CHECK_ERROR`,
}
//告警筛选
export const alarmFilterTypes = {
    RESET: 'RESET_ALARM_FILTER_PARAMS',
    CHANGE: 'CHANGE_ALARM_FILTER_PARAMS'
}