/**
 * Created by zmh on 2017/6/19.
 */
'use strict';
//fileInfo
// export const FILE_LIST_REQUEST = 'FILE_LIST_REQUEST';
// export const FILE_LIST_SUCCESS = 'FILE_LIST_SUCCESS';
// export const FILE_LIST_FAILURE = 'FILE_LIST_FAILURE';
//uploadFile
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE';
//deleteFile
export const DELETE_FILE_REQUEST = 'DELETE_FILE_REQUEST';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAILURE = 'DELETE_FILE_FAILURE';
//removeFile
export const REMOVE_FILE_REQUEST = 'REMOVE_FILE_REQUEST';
export const REMOVE_FILE_SUCCESS = 'REMOVE_FILE_SUCCESS';
export const REMOVE_FILE_FAILURE = 'REMOVE_FILE_FAILURE';
// //addFolder
// export const ADD_FOLDER_REQUEST = 'ADD_FOLDER_REQUEST';
// export const ADD_FOLDER_SUCCESS = 'ADD_FOLDER_SUCCESS';
// export const ADD_FOLDER_FAILURE = 'ADD_FOLDER_FAILURE';
// //collectedFile
// export const COLLECTED_FILE_REQUEST = 'COLLECTED_FILE_REQUEST';
// export const COLLECTED_FILE_SUCCESS = 'COLLECTED_FILE_SUCCESS';
// export const COLLECTED_FILE_FAILURE = 'COLLECTED_FILE_FAILURE';