//获取三维热点图
export const HEAT_MAP_REQUEST = 'HEAT_MAP_REQUEST';
export const HEAT_MAP_SUCCESS = 'HEAT_MAP_SUCCESS';
export const HEAT_MAP_FAILURE = 'HEAT_MAP_FAILURE';

//关注/取消关注
export const FOLLOW_SENSOR_REQUEST = 'FOLLOW_SENSOR_REQUEST';
export const FOLLOW_SENSOR_SUCCESS = 'FOLLOW_SENSOR_SUCCESS';
export const FOLLOW_SENSOR_FAILURE = 'FOLLOW_SENSOR_FAILURE';

//热点选择/热点取消选择
export const THREE_HOTSPOT_SELECT = 'THREE_HOTSPOT_SELECT';
export const THREE_HOTSPOT_DESELECT = 'THREE_HOTSPOT_DESELECT';

//更新实时数据
export const CLEAR_HOTSPOT_DATASOURCE='CLEAR_HOTSPOT_DATASOURCE';
export const INIT_HOTSPOT_DATASOURCE = 'INIT_HOTSPOT_DATASOURCE';
export const LOAD_LATEST_DATA = 'LOAD_LATEST_DATA';
export const LOAD_LATEST_VIB_DATA = 'LOAD_LATEST_VIB_DATA';
export const LOAD_LATEST_WARNING = 'LOAD_LATEST_WARNING';
export const UPDATE_PUSHED_DATA = 'UPDATE_PUSHED_DATA';
export const UPDATE_PUSHED_WARNING = 'UPDATE_PUSHED_WARNING';
export const UPDATE_FOLLOW_SENSOR = 'UPDATE_FOLLOW_SENSOR';

//结构物列表
export const THREE_STRUCTS_REQUEST='THREE_STRUCTS_REQUEST';
export const THREE_STRUCTS_SUCCESS='THREE_STRUCTS_SUCCESS';
export const THREE_STRUCTS_FAILURE='THREE_STRUCTS_FAILURE';


export const REFRESH_THREE_DATA = 'REFRESH_THREE_DATA';

export const CLEAR_HEAT_MAP_REQUEST = 'CLEAR_HEAT_MAP_REQUEST';