// 桥梁相关
export const BridgeApiTable = {

  findAllPartComponents: 'struct/{structId}/bridge/part/componets',
  getMembers: 'struct/{structId}/bridge/part/member',
  postMember: 'struct/bridge/part/member',
  putMember: 'struct/bridge/part/member/{memberId}',
  delMember: 'struct/bridge/part/member/{memberId}',
  getStructHasMembers: 'struct/{structId}/has/members',
  getStructMembers: 'struct/{structId}/members',

};

export const importColums = [
  { key: 'name', name: '桥梁名称' },
  { key: 'fileNo', name: '档案编号' },
  { key: 'region', name: '所在地区' },
  { key: 'way', name: '所在路名' },
  { key: 'maintainCate', name: '养护类别' },
  { key: 'maintainLevel', name: '养护等级' },
  { key: 'bridgeState', name: '运行状态' },
  { key: 'createdTime', name: '建成年月' },
  { key: 'sectionNum', name: '桥幅数' },
  { key: 'maintainCompany', name: '养护单位' },
  { key: 'strideOver', name: '跨越' },
  { key: 'totalCost', name: '总造价' },
  { key: 'manageCompany', name: '管理单位' },
  { key: 'buildCompany', name: '建设单位' },
  { key: 'designCompany', name: '设计单位' },
  { key: 'constructionCompany', name: '施工单位' },
  { key: 'supervisorCompany', name: '监理单位' },
  { key: 'roadLevel', name: '道路等级' },
  { key: 'bridgeType', name: '结构类型' },
  { key: 'bridgeWeight', name: '设计荷载' },
  { key: 'level', name: '等级' },
  { key: 'limitationCriteria', name: '限制标准' },
  { key: 'seismicIntensity', name: '抗震烈度' },
  { key: 'skewAngle', name: '正斜交角' },
  { key: 'bridgeSpans', name: '桥梁跨数' },
  { key: 'spanCombination', name: '跨径组合' },
  { key: 'deckArea', name: '桥面面积' },
  { key: 'bridgeLength', name: '桥梁总长' },
  { key: 'bridgeWidth', name: '桥梁总宽' },
  { key: 'roadwayWidth', name: '车行道净宽' },
  { key: 'sidewalkWidth', name: '人行道净宽' },
  { key: 'riverLevel', name: '河道等级' },
  { key: 'waterMaxDepth', name: '最高水位' },
  { key: 'waterNormalDepth', name: '常水位' },
  { key: 'remark', name: '备注' },
  { key: 'formMainbeam', name: '主梁形式' },
  { key: 'formBeam', name: '横梁形式' },
  { key: 'lossspanratioArch', name: '拱桥矢跨比' },
  { key: 'deckStructure', name: '桥面结构' },
  { key: 'expansionJointNum', name: '伸缩缝数量' },
  { key: 'longitudinalApproach', name: '引桥纵坡' },
  { key: 'mainbeamSize', name: '主梁尺寸' },
  { key: 'clearanceUnderMainspan', name: '主跨桥下净空' },
  { key: 'bearingType', name: '支座形式' },
  { key: 'deckPavementThickness', name: '桥面铺装厚度' },
  { key: 'longitudinalBridge', name: '主桥纵坡' },
  { key: 'crossApproach', name: '引桥横坡' },
  { key: 'mainbeamNum', name: '主梁数量' },
  { key: 'limitHeightBridge', name: '桥下限高' },
  { key: 'bearingNumber', name: '支座数量' },
  { key: 'formExpansionJoint', name: '伸缩缝形式' },
  { key: 'crossBridge', name: '主桥横坡' },
  { key: 'upperRemark', name: '上桥备注' },
  { key: 'pierForm', name: '桥墩形式' },
  { key: 'numberPiers', name: '桥墩数量' },
  { key: 'pierElevation', name: '桥墩标高' },
  { key: 'capBeamSize', name: '盖梁尺寸' },
  { key: 'pierBaseElevation', name: '基底标高' },
  { key: 'pierPlateSize', name: '底板尺寸' },
  { key: 'pierPileSize', name: '基桩尺寸' },
  { key: 'pierNumPiles', name: '基桩根数' },
  { key: 'pierRemark', name: '桥墩备注' },
  { key: 'abutmentForm', name: '桥台形式' },
  { key: 'numberAbutments', name: '桥台数量' },
  { key: 'abutmentElevation', name: '桥台标高' },
  { key: 'wingWallForm', name: '翼墙形式' },
  { key: 'abutmentBaseElevation', name: '基底标高' },
  { key: 'tableCapSize', name: '台帽尺寸' },
  { key: 'abutmentPlateSize', name: '底板尺寸' },
  { key: 'wingWallLength', name: '翼墙长度' },
  { key: 'abutmentPileSize', name: '基桩尺寸' },
  { key: 'abutmentNumPiles', name: '基桩根数' },
  { key: 'thicknessRetainingPlate', name: '挡土板厚度' },
  { key: 'abutmentRemark', name: '桥台备注' },
  { key: 'sizeWaterCollectport', name: '集水口尺寸' },
  { key: 'numberWaterCollectoutlets', name: '集水口数量' },
  { key: 'sizeDrainPipe', name: '泄水管尺寸' },
  { key: 'numberDrainPipe', name: '泄水管长度' },
  { key: 'totalLengthRailing', name: '栏杆总长' },
  { key: 'railingStructure', name: '栏杆结构' },
  { key: 'endPostSize', name: '端柱尺寸' },
  { key: 'typeRevetment', name: '护岸类型' },
  { key: 'typeSlope', name: '引坡挡墙类型' },
  { key: 'workRemark', name: '附属工程备注' },
  { key: 'waterPipe', name: '给水管' },
  { key: 'gasPipe', name: '燃气管' },
  { key: 'powerCable', name: '电力缆' },
  { key: 'communicationCables', name: '通信电缆' },
  { key: 'pipelineRemark', name: '附属管线备注' },

];
